# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carlos Rodriguez-Munoz
title: Aspiring Data Expert
email: carlos.rodriguez.munoz98@gmail.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  crodriguezm2016
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: c_rodriguezm
linkedin_username: crodriguezmunoz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Linktree
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-circle.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Carlos and I'm an aspiring Data Expert. I have prior internship experience in data analytics and my personal projects focus on data science. 
  I love learning and teaching others, so I am constantly pushing myself to work on new projects and to ask tons of questions!


  I am most passionate about: Using <mark>Data-Driven</mark> decision making, <mark>learning</mark>, and pour over style <mark>coffee</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stock Price Tracker Web App
        link: https://share.streamlit.io/crodriguezm2016/streamlit-apps/main/streamlit.py
        # link_text: Project Website
        additional_links:
          - title:  stockapp github
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This web app allows a user to enter a stock ticker, choose the type of data they would like to pull (Daily, Weekly, Monthly, or Quarterly) and how far back they would like to pull data from.
          Once these are selected, data is pulled from Yahoo! Finance and graphs for the opening, high, low, and closing prices, as well as the volume of shares traded are displayed
          
          I created in <mark>Python</mark> and utilized packages such as **pandas** and **yfinance**.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Motional
        link: motional.com
        # link_text: boringcompany.com
        sub_title: TA/HR Data Analysis Intern
        caption: June 2021 - Present
        quote: >
          We're making driverless vehicles a safe, reliable, and accessible reality.
        description: | # this will include new lines to allow paragraphs
            At Motional, I specialized in providing data-driven reports to the Human Resource, Talent Acquisition, and Leadership teams. 
            I primarily used *Google Sheets* and *Microsoft Excel* to conduct analytics and regression models. 
            I also used *Google Data Studio* to create beautiful automated dashboards which were regularly sent out to the heads of the Engineering departments.

      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Walla Walla University
        caption: June 2016 - December 2021
        sub_title: BA Mathematics
        description: | # this will include new lines to allow paragraphs
          During my time at Walla Walla University, I developed my deep passion for Math, data, and learning! My main emphasis was in Applied Mathematics, specifically, differential equations and statistics.
          In additon to my major in Mathematics, I also completed a minor in Economics where I had a particular interest in financial markets and institutions.

          I spent a lot of my free time chatting with anyone and everyone, as well as helping people with Math. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Coffee: Currently enjoying a washed single origin from Ethopia by Roseline
      - Gaming: Lately, I've been playing Gunfire Reborn and League of Legends
      - Learning: Teaching myself some machine learning concepts from freeCodeCamp

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
