# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carlos Rodriguez-Munoz
title: Data Analyst, People Analytics
#email: carlos.rodriguez.munoz98@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  crodriguezm2016
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: c_rodriguezm
linkedin_username: crodriguezmunoz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-globe
  #url: https://docs.google.com/document/d/1AEW-UKNQ445hfGUcT9RyMyJJDnu9E1sqZbCFf51LWzQ/edit?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/0001-modified.png
about_content: | # this will include new lines to allow paragraphs
  Hey! I'm Carlos and I'm aspiring to become a Data Expert who can find ways to give back to my community through teaching, mentoring, and more. 
  Starting college, I was studing nursing which made me take a statistics course and I fell in love with math.
  Next thing I knew, I had switch my major and the rest is history. Part way through college, I took a year off, moved to Denmark and spent the year working as a dean
  and teacher. This experience sparked my love for teaching, mentoring, and traveling. When I got back, I continued my degree in Mathematics and added a minor in Economics.
  I started working as a Teacher's Assistant for the Math and Business departments on campus which gave me the opportunity to teach and mentor students.
  During my final summer in college I got an internship at Motional where I worked as a Data Analyst on the Talent Acquisition team. 
  About 2 months before I graduated, I was extremely lucky to get an offer with New Relic and I have been working full time as a Data Analyst in People Analytics since then.

  In my free time, I spend most of my time learning, mentoring, making coffee, and gaming. Part of my learning involves working on new personal projects which you can find on
  my GitHub and even some down below. I have a huge passion for helping others find jobs and internships so I work with students from my alma mater to do resume reviews, carreer counseling,
  and networking. I am really into coffee as well! I just got an espresso machine (Lucca A53 Mini) so I have been making tons of cappuccino and other espresso drinks. Gaming is my main hobby for pleasure.
  I am pretty competitive so I wouldn't say it is always relaxing but I sure do enjoy it! For more information and details on this stuff, look at the final section on my website.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: top-middle
        title: Spotify Wrapped
        link: https://spotifywrap-carlosrodriguezm.streamlit.app/
        link_text: Streamlit App
        additional_links:
          - title:  Github SpotifyWrapped
            icon: fab fa-github
            url: https://github.com/crodriguezm2016/SpotifyWrapped
        description: | # this will include new lines to allow paragraphs
          I love seeing my listening stats and most listened to artists from Spotify at the end of the year. That got me thinking, what if I could see my Spotify Wrapped at any point in the year?
          This project guides users on how to download their Spotify data, allows them to upload it to the web app and then let's them customize their data experience.
          This project is one of my most recent projects so it was cool for me to be able to apply some new things I had learned like using lambdas and trying to create an experience that people would enjoy using.
          I have more ideas that I would like to implement with this project, so hopefully more to come soon.
          
          I created this project in **VS Code** using **Python**, utilizing packages such as **streamlit**, **pandas**, and **plotly**.
    
      - layout: top-middle
        title: COVID-19 vs 2020 Voting Data by County
        link: https://colab.research.google.com/drive/11g2WB9-6fIW4piMyy8u7KNUTkLE7x_xK?usp=sharing
        link_text: Runable Google Colab Link
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
          #  icon: fas fa-globe
          #  url: https://colab.research.google.com/drive/19aVPWWbxLtchqkNbnelDMcQVPzLGyl32?usp=sharing
        description: | # this will include new lines to allow paragraphs
          This coding project takes voting data from the 2020 Presidential Election and compares it to COVID-19 death rates in the same county.
          I created a Choropleth map by county to show the percent of vote share that Joe Biden or Donald Trump received, as well as the death rate in that county from Covid.
          FIPS and a GeoJSON file are used to determine the county designations.
          A few different visualizations are made, with different focuses on the voting data vs the death rate data. 
          Covid data is pulled from the New York Times.
          
          I created this project in **Google Colab** using **Python** and **Jupyter Notebooks**, utilizing packages such as **pandas** and **plotly**.
    
      - layout: top-middle
        title: Predicting and Modeling Pulic Opinion
        link: https://drive.google.com/file/d/1pXVFEika4Dr6eVNw8nBse2F8aiIk3lXz/view
        link_text: Paper Typeset with LaTeX
        additional_links:
          - title:  senior project github
            icon: fab fa-github
            url: https://github.com/crodriguezm2016/Predicting-and-Modeling-Public-Opinion
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is an R markdown file of my senior project. 
          This project used regression techniques and parameter estimation in order to fully build out a mathematical model of 3 Differential Equations that would predict and model public opinion polling. 
          Training and Testing Data was from the Gallop Polling Organizaiton.
          
          I created this project in **R Studio** using the **R programming language** and utilized packages such as **plotly**, **deSolve**, **ggplot2**, **plot3D**, and **rootSolve**.
          
      - layout: top-middle
        title: Stock Price Tracker Web App
        link: https://share.streamlit.io/crodriguezm2016/stock-app/main/stockapp.py
        link_text: Interactive Web App Link
        additional_links:
          - title:  stockapp github
            icon: fab fa-github
            url: https://github.com/crodriguezm2016/Stock-App
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This web app allows a user to enter a stock ticker, choose the type of data they would like to pull (Daily, Weekly, Monthly, or Quarterly) and how far back they would like to pull data from.
          Once these are selected, data is pulled from Yahoo! Finance and graphs for the opening, high, low, and closing prices, as well as the volume of shares traded are displayed.
          
          I created this project in **VS Code** using **Python** and utilized packages such as **pandas** and **yfinance**.
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Analyst, People Analytics
        link: https://newrelic.com/
        # link_text: boringcompany.com
        sub_title: New Relic
        caption: October 2021 - Present
        quote: >
          We’re data nerds that do everything for the love of software.
        description: | # this will include new lines to allow paragraphs
            At New Relic, I primarily work with the HRBP and Executive teams to provide meticulous reporting on People data. This includes but is not limited to,
            data pertaining to annual review cycle, ad hoc requests about People Metrics, Enablement projects to raise data literacy within our teams, compensations reporting and planning, and more.
            The main tools I use on a day to day basis include, **Python**, **R**, **GitHub**, **Google Sheets**, **Microsoft Excel**, **Asana** and **Slack**.
            Occasionally, I use **Tableau** and **SQL**. Some technical responsibilites that I take on include building and maintaining data pipelines through APIs,
            creating scripts in Python and R to clean and upload data to Google Sheets for a non-technical audience to utilize, and building out pages for our wiki using Markdown
            and CSS to bring clear definitions for the metrics that we report on. 
            
      - layout: left
        title: TA/HR Data Analysis Intern
        link: motional.com
        # link_text: boringcompany.com
        sub_title: Motional
        caption: June 2021 - October 2021
        quote: >
          We're making driverless vehicles a safe, reliable, and accessible reality.
        description: | # this will include new lines to allow paragraphs
            At Motional, I specialized in providing data-driven reports to the Human Resource, Talent Acquisition, and Leadership teams. 
            I primarily used **Google Sheets** and **Microsoft Excel** to conduct analytics and regression models on recruiting data from **GreenHouse**. 
            I also used **Google Data Studio** to create beautiful automated dashboards which were regularly sent out to the heads of the Engineering departments.

      - layout: left
        title: Teacher's Assistant
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2020 - October 2021
        description: | # this will include new lines to allow paragraphs
            As a Teacher's Assistant, I assisted **4** different professors in both the **Math** and **Business** departments at my university.
            I taught the lab component of the **Intro to Statistics** class to over **20** students each week. 
            I also provided constructive feedback on coursework to over **80** students each week and held review session before exams for classes such as **Probability & Statistics**, **Intro to Statistics**, the **Calculus** sequence, **Investments**, and **Economics**.

      - layout: left
        title: Peer Tutor
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2019 - October 2021
        description: | # this will include new lines to allow paragraphs
            As a peer tutor, I became a **CRLA Level 1 Certified Peer Tutor**.
            I helped over **10** students each week, both in person and virtually over **Microsoft Teams** in areas such as **Statistics**, **Calculus**, **R Programming**, and **Differential Equations**.

      - layout: left
        title: Teacher and Assistant Dean
        link: https://www.vejlefjordskolen.dk/
        # link_text: boringcompany.com
        sub_title: Vejlefjordskolen
        caption: August 2018 - June 2019
        description: | # this will include new lines to allow paragraphs
            I moved to **Denmark** for a year to work as a **Teacher** and **Assistant Dean**. 
            During the day, I taught **Math**, English, **Computers**, and E-sports to over **30** students between **2nd** grade and **8th** grade.
            In the evenings, I would foster mentorships with the boarding students, tutor, and perform nightly checks for over **50** students. 
            
            PS. This looks intimidating and hard to say and well it kind of is but here is my best pronunciation guide: Vey - le - fyor - sko - len
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Walla Walla University
        caption: June 2016 - December 2021
        sub_title: BA Mathematics
        description: | # this will include new lines to allow paragraphs
          During my time at Walla Walla University, I developed my deep passion for math, data, and learning! My main emphasis was in Applied Mathematics, specifically, differential equations and statistics.
          In addition to my major in Mathematics, I also completed a minor in Economics where I had a particular interest in financial markets and institutions.

  - title: Skills and Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      My main skill set includes:
      - Math: My strongest areas are in **Statistics** and **Differential Equations**
      - Programming: **Python** is my strong programming language. I am continuing to learn and develop my **SQL** and **R** skills.
      - Data Analytics: I have extensive experience using **Google Sheets**, **Excel**, and **Google Data Studio**.
      - Remote Work: I am comfortable with **Microsoft Teams**, **Zoom**, **G-Suite**, **Slack**, and **Overleaf** for **LaTeX**.
      - Languages: My native language is English, I am somewhat conversational in Danish, and am at a beginner level with Spanish.

      The certifications that I currently hold are below and to view them, click [here](https://drive.google.com/drive/folders/1Cd9c9oaLP5R89Ge4Ch1LaYf0udIcNyBq?usp=sharing).
      - Learning **Python** by LinkedIn Learning
      - Learning **SQL** Programming by LinkedIn Learning
      - Learning **Excel**: Data Analysis by LinkedIn Learning
      - Learning **Google Data Studio** for Marketers by LinkedIn Learning
      - **Data Visualization** for Data Analysis and Analytics by LinkedIn Learning

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some more details about things I have been interested in lately:
      - Coffee: Currently, on espresso, I am drinking the Blue Orchid Blend from Huckleberry Roasters in Denver, CO.
      - Learning: Teaching myself some machine learning concepts from DataCamp. Also working on getting better at R and the tidyverse since I am currently more comfortable with Python.
      - Math: My math learning has taken a backseat lately but hoping to hop into some more statistics and distribution types.
      - Backpacking: Still reminiscing about the Tour du Mont Blanc which I did back in summer of 2019, pics of my trip can be found [here](https://drive.google.com/drive/folders/1pDKwUIW73xAk_3IKdI7oeG6KVyAbrZWW?usp=sharing).
      - Traveling: I've visited over 20 countries and am super excited to visit even more! Some of my favorite cities are Copenhagen (I'm biased), Venice, and Prague.
      - Gaming: Been playing a ton of Teamfight Tactics and managed to hit Diamond 3 for set 6! Check it out [here](https://lolchess.gg/profile/na/carlitos). I also just got Pokemon Legends Arceus so I expect to be playing that quite a bit as well.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
