# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carlos Rodriguez-Munoz
title: Aspiring Data Expert
email: carlos.rodriguez.munoz98@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  crodriguezm2016
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: c_rodriguezm
linkedin_username: crodriguezmunoz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Linktree
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-circle.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Carlos and I'm an aspiring Data Expert. I have prior internship experience in data analytics and my personal projects focus on data science. 
  I love learning and teaching others, so I am constantly pushing myself to work on new projects and to ask tons of questions!


  I am most passionate about: Using **Data-Driven** decision making, **mathematics**, **learning**, and pour over style **coffee**.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stock Price Tracker Web App
        link: https://share.streamlit.io/crodriguezm2016/streamlit-apps/main/streamlit.py
        # link_text: Project Website
        additional_links:
          - title:  stockapp github
            icon: fab fa-github
            url: https://github.com/crodriguezm2016/Stock-App
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This web app allows a user to enter a stock ticker, choose the type of data they would like to pull (Daily, Weekly, Monthly, or Quarterly) and how far back they would like to pull data from.
          Once these are selected, data is pulled from Yahoo! Finance and graphs for the opening, high, low, and closing prices, as well as the volume of shares traded are displayed
          
          I created this project in <mark>Python</mark> and utilized packages such as **pandas** and **yfinance**.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TA/HR Data Analysis Intern
        link: motional.com
        # link_text: boringcompany.com
        sub_title: Motional
        caption: June 2021 - Present
        quote: >
          We're making driverless vehicles a safe, reliable, and accessible reality.
        description: | # this will include new lines to allow paragraphs
            At Motional, I specialized in providing data-driven reports to the Human Resource, Talent Acquisition, and Leadership teams. 
            I primarily used **Google Sheets** and **Microsoft Excel** to conduct analytics and regression models on recruiting data from **GreenHouse**. 
            I also used **Google Data Studio** to create beautiful automated dashboards which were regularly sent out to the heads of the Engineering departments.

      - layout: left
        title: Teacher's Assistant
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2020 - Present
        description: | # this will include new lines to allow paragraphs
            As a Teacher's Assistant, I assisted **4** different professors in both the **Math** and **Business** departments at my university.
            I taught the lab component of the **Intro to Statistics** class to over **20** students each week. 
            I also provided constructive feedback on coursework to over **80** students each week and held review session before exams for classes such as **Probability & Statistics**, **Intro to Statistics**, the **Calculus** sequence, **Investments**, and **Economics**.

      - layout: left
        title: Peer Tutor
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2019 - Present
        description: | # this will include new lines to allow paragraphs
            As a peer tutor, I became a **CRLA Level 1 Certified Peer Tutor**.
            I helped over **10** students each week, both in person and virtually over **Microsoft Teams** in areas such as **Statistics**, **Calculus**, **R Programming**, and **Differential Equations**.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Walla Walla University
        caption: June 2016 - December 2021
        sub_title: BA Mathematics
        description: | # this will include new lines to allow paragraphs
          During my time at Walla Walla University, I developed my deep passion for math, data, and learning! My main emphasis was in Applied Mathematics, specifically, differential equations and statistics.
          In additon to my major in Mathematics, I also completed a minor in Economics where I had a particular interest in financial markets and institutions.

          I spent a lot of my free time chatting with anyone and everyone, as well as helping people with Math. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some more details about things I have been interested in lately:
      - Coffee: Currently enjoying a washed single origin from Ethopia by Roseline
      - Gaming: Lately, I've been playing Gunfire Reborn and League of Legends
      - Learning: Teaching myself some machine learning concepts from freeCodeCamp
      - Math: Mathematical Modeling and Differential Equations have been top of my list lately
      - Backpacking: Still reminicing about the Tour du Mont Blanc which I did back in summer of 2019, pics of my trip can be found [here](https://drive.google.com/drive/folders/1pDKwUIW73xAk_3IKdI7oeG6KVyAbrZWW?usp=sharing).

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
